name: Run Python tests

on: [push]

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.6','3.7','3.8','3.9','3.10']

    steps:
      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "America/Chicago"
      - uses: actions/checkout@v3
      - name: Set up Python ${{ python_version }}
        uses: actions/setup-python@v4
        with:
          python-version: $${{ python_version }}
      - name: Install dependencies
        run: pip install pytest pytest-md pytest-emoji
      - uses: pavelzw/pytest-action@v2
        with:
          emoji: false
          verbose: false
          job-summary: true

